name: force-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - napari
  - numpy
  - pandas
  - pyqt
  - scikit-image
  - scipy
  - trimesh
  - pip:
    - foambryo[viewing]