[project]
name = "embo-bia-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "foambryo[viewing]>=0.3.5",
    "jupyterlab>=4.4.6",
    "napari[pyqt6]>=0.6.4",
]
